---
- name: Check if aptitude is already installed
  stat:
    path: /usr/bin/aptitude
  register: aptitude_installed
  tags:
    - apt

- name: Install dependencies for apt module
  command: apt-get install -y aptitude
  when: (aptitude_installed is defined and not aptitude_installed.stat.exists)
  tags:
    - apt

- name: Upgrade the installed packages
  apt: update_cache=yes upgrade=yes
  tags:
    - apt

- debug: msg="If on vagrant - reboot the machine; login; run `sudo /etc/init.d/vboxadd setup` to repare the vagrant specifics."
